/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Habibullah
 */
public class v_Menu extends javax.swing.JFrame {
    
    public v_Menu() {
        initComponents();
    }
    
    public JButton getMulai() {
        return mu;
    }
    
    public JButton getNilai() {
        return ni;
    }
    
    public JButton getBantuan() {
        return bt;
    }
    
    public JButton getTentang() {
        return tt;
    }
    
    public JButton getKeluar() {
        return kl;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mu = new javax.swing.JButton();
        ni = new javax.swing.JButton();
        bt = new javax.swing.JButton();
        tt = new javax.swing.JButton();
        kl = new javax.swing.JButton();
        gbr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/b.mulai.png"))); // NOI18N
        mu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muActionPerformed(evt);
            }
        });
        getContentPane().add(mu, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 195, 360, 70));

        ni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/b.nilai.png"))); // NOI18N
        ni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                niActionPerformed(evt);
            }
        });
        getContentPane().add(ni, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 275, 360, 70));

        bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/b.bantuan.png"))); // NOI18N
        bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActionPerformed(evt);
            }
        });
        getContentPane().add(bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 353, 360, 70));

        tt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/b.tentang.png"))); // NOI18N
        tt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttActionPerformed(evt);
            }
        });
        getContentPane().add(tt, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 433, 360, 70));

        kl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/b.keluar.png"))); // NOI18N
        kl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                klActionPerformed(evt);
            }
        });
        getContentPane().add(kl, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, 360, 70));

        gbr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gbr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        getContentPane().add(gbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void muActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muActionPerformed
        v_Mulai m = new v_Mulai();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_muActionPerformed

    private void ttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttActionPerformed
        v_Tentang t = new v_Tentang();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ttActionPerformed

    private void niActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_niActionPerformed
        v_Nilai n = new v_Nilai();
        n.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_niActionPerformed

    private void btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActionPerformed
        v_Bantuan b = new v_Bantuan();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btActionPerformed

    private void klActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_klActionPerformed
        int selectedOption = JOptionPane.showConfirmDialog(null,
        "Apakah kamu akan menutup permainan?", "Tutup Aplikasi", JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION) {
        System.exit(0);
        }
        
//        v_Menu mn = new v_Menu();
//        v_Loading l2 = new v_Loading();
//        mn.setVisible(false);
//        l2.setVisible(true);
//        this.dispose();
//        
//        try {
//            for (int i = 0; i <= 100; i++) {
//                Thread.sleep(50);
//                l2.P.setText(Integer.toString(i)+"%");
//                l2.LBar.setValue(i);
//                if(i==100){
//                    System.exit(0);
//                }
//            }
//            } catch (InterruptedException e) {  
//            }
    }//GEN-LAST:event_klActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
          

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt;
    private javax.swing.JLabel gbr;
    private javax.swing.JButton kl;
    private javax.swing.JButton mu;
    private javax.swing.JButton ni;
    private javax.swing.JButton tt;
    // End of variables declaration//GEN-END:variables
}
